# Generated by Django 5.2.4 on 2025-07-15 05:38

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_tag_singer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='singer',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
