# Generated by Django 5.2.4 on 2025-07-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_singer_image_alter_singer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
    ]
